### ISSUE TITLE
Add a "Relaunch" remote environment button

### ISSUE THREAD

**Issue by rlamana** [okteto/docker-desktop-extension#70]
**Is your feature request related to a problem? Please describe.**
Once an environment has been launched, there is no way to relaunch it again unless you stop it, select the docker-compose file again and launch as you did the first time.

**Describe the solution you'd like**
Since we already have the path to the docker-compose file,  a "Relaunch" button in the extension UI could trigger a new `okteto up` call.

![Relaunch Button Mock](https://user-images.githubusercontent.com/237819/191718567-a2ee7ae6-41c6-4153-9da0-7ccaed887abf.png)

**Additional context**
The relaunch functionality should be as simple as updating the "environment" in the Okteto React context just like it is done here: https://github.com/okteto/docker-desktop-extension/blob/main/client/src/contexts/Okteto.context.tsx#L58

**Comment by HeartBeat1608** [comment]
Hey @rlamana, I would like to give this a go. Is there anything else apart from the stated, that you would like me to know on this?

**Comment by rlamana** [comment]
@HeartBeat1608 it's already assigned to you, thanks for participating!
